### ISSUE TITLE
[ChickenKyiv Project][Main Task][Not finished]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/types#1]
[Link to current DB Shema](https://chickenkyiv.gitbook.io/documentation/database-schemes/chickenkyiv-schema)

- [ ] Models
- [ ] Relations
- [ ] CRUD Methods for each model

#### Models
[This is a place where we defined our models for this API Server] (https://github.com/ChickenKyiv/recipe-api-only/tree/master/server/models)
- [ ] Allergy
- [ ] Course
- [ ] Cuisine
- [ ] Diet
- [ ] Holiday
- [ ] Day
- [ ] Department
- [ ] Ingredient
- [ ] Grocery
- [ ] Menu
- [ ] Nutritions
- [ ] Email
- [ ] Recipe
- [ ] Account
```
  /account/login
	/account/logout
	/account/update
	/account/changePassword
	/account/delete
	/account/language
	/account/signup

	// todo
	/account/verify
	/account/recover
	/account/recover/password
	/account/changeEmail
  ```

#### Relations
For example we'll review [Recipe Model schema](https://github.com/ChickenKyiv/recipe-api-only/blob/master/server/models/recipe.json)
We'll find section, related to [relations](https://github.com/ChickenKyiv/recipe-api-only/blob/master/server/models/recipe.json#L44-L99)
For each of this relation we should create a constant.
like
`export const RECIPE_ALLERGIES_LIST = 'RECIPE_ALLERGIES_LIST'`
- [ ] Recipe
- [ ] User
- [ ] Ingredient
- [ ] Grocery
- [ ] Department
- [ ] Day

#### Additional Methods for each model
[User controller](https://github.com/ChickenKyiv/recipe-api-only/blob/master/server/controllers/user-controller.js
[DBShema](https://chickenkyiv.gitbook.io/documentation/database-schemes/chickenkyiv-schema)

- [ ] Models
- [ ] Relations
- [ ] CRUD Methods for each model

#### Models
[This is a place where we defined our models for this API Server] (https://github.com/ChickenKyiv/recipe-api-only/tree/master/server/models)
- [ ] Allergy
- [ ] Course
- [ ] Cuisine
- [ ] Diet
- [ ] Holiday
- [ ] Day
- [ ] Department
- [ ] Ingredient
- [ ] Grocery
- [ ] Menu
- [ ] Nutritions
- [ ] Email
- [ ] Recipe
- [ ] Account
```
  /account/login
	/account/logout
	/account/update
	/account/changePassword
	/account/delete
	/account/language
	/account/signup

	// todo
	/account/verify
	/account/recover
	/account/recover/password
	/account/changeEmail
  ```

#### Relations
For example we'll review [Recipe Model schema](https://github.com/ChickenKyiv/recipe-api-only/blob/master/server/models/recipe.json)
We'll find section, related to [relations](https://github.com/ChickenKyiv/recipe-api-only/blob/master/server/models/recipe.json#L44-L99)
For each of this relation we should create a constant.
like
`export const RECIPE_ALLERGIES_LIST = 'RECIPE_ALLERGIES_LIST'`
- [ ] Recipe
- [ ] User
- [ ] Ingredient
- [ ] Grocery
- [ ] Department
- [ ] Day

#### Additional Methods for each model
[User controller](https://github.com/ChickenKyiv/recipe-api-only/blob/master/server/controllers/user-controller.js)
Here you can find few methods, related to sign up process. You should create set of constants, for each of this methods
- [ ]

https://chickenkyiv.gitbook.io/documentation/chickenkyiv-methods

CK API
https://github.com/ChickenKyiv/recipe-api-only/blob/master/RemoteMethods.md

https://chickenkyiv.gitbook.io/documentation/chickenkyiv-free-menu-release

)
Here you can find few methods, related to sign up process. You should create set of constants, for each of this methods
- [ ]

https://chickenkyiv.gitbook.io/documentation/chickenkyiv-methods

CK API
https://github.com/ChickenKyiv/recipe-api-only/blob/master/RemoteMethods.md

https://chickenkyiv.gitbook.io/documentation/chickenkyiv-free-menu-release

**Comment by Yoimer** [comment]
I am checking all this structure. What would I need doing with this? I am excited for this. Thanks a lot

**Comment by atherdon** [comment]
@Yoimer from what section od you want to start?

**Comment by Yoimer** [comment]
You just tell me which one.

**Comment by Yoimer** [comment]
Which skills do I would need for doing this sort of project? Only JavaScript? What exactly would I be doing here?
