### ISSUE TITLE
[ChickenKyiv][relations]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/types#5]
#1 

Please take a look at [ChickenKyiv DB Schema Diagram](https://chickenkyiv.gitbook.io/documentation/database-schemes/chickenkyiv-schema). 
You'll need to create a set of JS constants. Each constant will be related to one relation.

For example we'll review [Recipe Model schema](https://github.com/ChickenKyiv/recipe-api-only/blob/master/server/models/recipe.json)
We'll find section, related to [relations](https://github.com/ChickenKyiv/recipe-api-only/blob/master/server/models/recipe.json#L44-L99)

So result of reviewing Recipe Table will be line, similar to this: 
`export const RECIPE_ALLERGIES_LIST = 'RECIPE_ALLERGIES_LIST'`

List of Models with relations
- [ ] Recipe
- [ ] User
- [ ] Ingredient
- [ ] Grocery
- [ ] Department
- [ ] Day

**Comment by atherdon** [comment]
This is link to a file, where you'll commit your changes: https://github.com/GroceriStar/types/blob/master/ChickenKyiv/api/relations.js

**Comment by atherdon** [comment]
@Yoimer you can grab this task. yes, it'll require only basic JS skills for now. if later you'll be interested to dig more and help us with more complex work - we'll talk and find other tasks for you.

**Comment by Yoimer** [comment]
Ok, I will give it a try. Let you know later.
